### ISSUE TITLE
When providing text input, need codepage as the parameter

### ISSUE THREAD

**Issue by sevaa** [emn178/online-tools#16]
Hash functions operate on byte arrays. Converting a text string to a byte array is impossible without specifying a codepage. The app, as it is now, neither advertises the codepage it uses nor allows the user to specify one.

Please provide that capability, with at least UTF-8 and UTF-16LE as options.

**Comment by Isirovamaria** [comment]
Здравствуйте почему не выводити деньги

**Comment by Isirovamaria** [comment]
@emn178 
Через восколько выводити

**Comment by sevaa** [comment]
@Isirovamaria Доброго времени суток, Вы ко мне обращаетесь? О каких именно деньгах речь?

**Comment by emn178** [comment]
added this feature
