### ISSUE TITLE
Web Site https://emn178.github.io/online-tools/sha256.html with new results

### ISSUE THREAD

**Issue by magicwackes** [emn178/online-tools#31]
Since 'few days' the site is not working anymore on Internet-Explorer. (Intended obviously)
Using other Browsers I do not get different results for SHA256 determination.
Former result: Input(Hex) 006030323031BFA577FD  OUTPUT: 12992276..blabla
Current result: Input(Hex) 006030323031BFA577FD OUTPUT: ceaa56ba61..blabla

https://emn178.github.io/online-tools/sha256.html?input_type=hex&input=006030323031BFA577FD&hmac_enabled=1&hmac_input_type=hex

It seems something went wrong disabling IE Support and adding "Hex" in combination with "hmac"

**Comment by magicwackes** [comment]
Typo:      I do not get different results for SHA256 determination.
Correct:  I do get different results for SHA256 determination.

**Comment by emn178** [comment]
What version of IE you are using?

**Comment by magicwackes** [comment]
It is a remote controlled IE instance from Excel VBA to collect CRC32 and SHA256 results. It is the ieframe.dll (the Microsft Internet Explorer Control) Not sure if that is IE11.
Since few weeks remote control does not work anymore and I switched to Selenium solution to remotecontrol sha256.html WebSite. But now I realize, that the results for SHA256 (HEX Input) does not give the same values as before for already created data since March this year.
That WebSite https://www.liavaag.org/English/SHA-Generator/ calculates my HexInput as before.
So it looks like that recent adaptions led to drawbacks in the SHA256 (potentielly others as well) results. Maybe the data is not interpeted as HEX Input even if the selection is done the right way.

**Comment by emn178** [comment]
Hi, fixed some bugs, I test it can work IE9+. please try again. Thanks for reporting.

**Comment by magicwackes** [comment]
The SHA256.html is working again.
I have verified with sample data (Output is known) that 'your' Outputs are matching again. Congrats for the fast fix.
