### ISSUE TITLE
could you add 'Output Type' for Decodes

### ISSUE THREAD

**Issue by WBPark9** [emn178/online-tools#32]
![image](https://github.com/emn178/online-tools/assets/82030470/ce086ed6-7002-4ecb-9eaa-70ffe17a726b)
![image](https://github.com/emn178/online-tools/assets/82030470/ce8257b5-358d-4a0a-9282-7f696c5f920c)

unable to decode Base32, Base58 or Base64 to hex so please add 'Output Type' selectors that would be so nice

**Comment by emn178** [comment]
added this feature, please try it.

**Comment by emn178** [comment]
added this feature, too
> Also, instead of all the separate encode/decode pages, it'd be much more convenient to just have a drop-down menu for the input type and a two-way-switch like on Google Translate to swap input/output.
