### ISSUE TITLE
Please, make js implementation for Blake3 in browsers

### ISSUE THREAD

**Issue by leonbakadorov** [emn178/online-tools#35]
So many years have passed since the release of Blake3, but there is still no implementation in JS for browsers. Or is there?

Can you add Blake3 to your collection?

**Comment by emn178** [comment]
Added this feature. please try it.

**Comment by leonbakadorov** [comment]
> Added this feature. please try it.

[emn178](https://github.com/emn178),

I noticed that at the end of blake3.js there is jquery code - I expected execution in pure JS.

It’s also not entirely clear how to use this library in your own projects - could you show examples of connecting the library and available methods?

Thank you)

**Comment by emn178** [comment]
I use this library https://github.com/rvgrinsven/blake3-js, but its distribution https://cdn.jsdelivr.net/npm/blake3-js@0.0.5/dist/main.min.js is not umd. I modified `module.export` to `window.blake3`, and it can be used in browser.

**Comment by emn178** [comment]
I split the code into two files. This file includes only blake3-js library:
https://emn178.github.io/online-tools/js/blake3-js.min.js
