### ISSUE TITLE
Hex to MD5

### ISSUE THREAD

**Issue by htakawira** [emn178/online-tools#42]
When i create a hash fro your site (https://emn178.github.io/online-tools/) i get the correct value e.g.

Input type Hex 
When i input 
6325d34a2cc106b323324e1540bfac08dafed800ba6906c3027f49315dab937c89e8c0d9c227b4c2a416de88ac356acc91e66cb80c854a716453603ea4a9bdd6c38755d8de44179b8d080041020c4c2548718af1f818b343b21bf6209db1523e25e9769d386a4224337d179fe8482d82c68800df8f579e714ab1ef3e421ef817

I get Hash

c2d166dbffc6cb19a570aee7a6400e24

I am having a challenge replicating this using php to get the same response

May i please know the php code to convert this Hex to MD5

**Comment by emn178** [comment]
https://www.codecademy.com/resources/docs/php/string-functions/hex2bin
```PHP
md5(hex2bin($hex))
```

**Comment by htakawira** [comment]
Sir , Thank you very much. You are gold
Honestly Thank you

md5(hex2bin($hex)) worked
