### ISSUE TITLE
support double-SHA256

### ISSUE THREAD

**Issue by ppKrauss** [emn178/online-tools#6]
The **SHA256d** is the standard hash for [Bitcoin](https://en.bitcoin.it/wiki/Block_hashing_algorithm) (see also its [common standards](https://en.bitcoin.it/wiki/Protocol_documentation#Common_standards)) and for the Brazilian registry offices (see e.g. [Uniproof](https://uniproof.com.br/)).

In Javascript will be something as  
```javascript
hash = hashlib.sha256(hashlib.sha256(document_bin).digest()).digest()
```
I can help to implement if necessary... But is very simple for a tool that has already implemented SHA256.

**Comment by BrendanSluke** [comment]
Hi I've created something fairly simple on my web tools site, [SHA256d Hash Generator Online](http://buncha.tools/online-hash-generator-sha256d)

**Comment by emn178** [comment]
added this page https://emn178.github.io/online-tools/double_sha256.html
