### ISSUE TITLE
MD4 or MD4 File

### ISSUE THREAD

**Issue by yoonghm** [emn178/online-tools#7]
Hi, I tried to use the service to hash "testingPassword" which is encoded in UTF-16LE. The generated hash code is not correct.

In Python, the hash code is `32910df84fa6579a5d0865fca64f1190`.

However the em178.github.io gives `05c90f1db64d14923f2c126fe1a57082`.  I copied the content from Microsoft Word and the file is written using UTF-16LE.

I use MD4 file, it gives me `6875f3e20a30fe64b49658b2bfe5bf13` instead.

The file is available from https://raw.githubusercontent.com/yoonghm/misc/master/myfile-utf18le.txt

**Comment by emn178** [comment]
File Checksum will process it in bytes. The behavior is different from hash plain text. Make sure which one is you want. Read plain text and hash or hash entire file.
