### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Heptazhou** [emn178/online-tools#8]
https://github.com/emn178/online-tools/blob/c50f9a6dc82c1f6a7dda0cbcc1606f85d387694a/js/main.js#L41 https://github.com/emn178/online-tools/blob/c50f9a6dc82c1f6a7dda0cbcc1606f85d387694a/app/contents/js/main.js#L41

A typo I guess.

**Comment by dinhanhx** [comment]
Agree with you, `does` not `dose`

**Comment by emn178** [comment]
done
